### ISSUE TITLE
scoring.py in the Elrya Pipelines module fails when ran in pipeline

### ISSUE THREAD

**Issue by aokugel** [RedHatQuickCourses/rhods-qc-apps#28]
This is the error when the scoring.py file is run individually

```
Traceback (most recent call last):
  File "/home/akugel/Documents/projects/lc_practice/rhoai-lab/scoring.py", line 30, in <module>
    predict(data_folder='/home/akugel/Documents/projects/lc_practice/rhoai-lab/data')
  File "/home/akugel/Documents/projects/lc_practice/rhoai-lab/scoring.py", line 12, in predict
    raw_results = session.run([], {'dense_input': X})[0]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akugel/anaconda3/lib/python3.11/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 216, in run
    self._validate_input(list(input_feed.keys()))
  File "/home/akugel/anaconda3/lib/python3.11/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 198, in _validate_input
    raise ValueError(
ValueError: Required inputs (['dense_3_input']) are missing from input feed (['dense_input']).
```

The issue i believe is here:

https://github.com/RedHatQuickCourses/rhods-qc-apps/blob/main/5.pipelines/elyra/scoring.py#L12

**Comment by bbalakriz** [comment]
+1. The input name provided in the code should be updated to dense_3_input. Otherwise, the pipeline run fails with this error.

**Comment by rsriniva** [comment]
fixed in main. dupe issue #29
